export const mockAPI = [
  {
    id: 1,
    firstName: "Leo",
    lastName: "Messi",
    age: 34,
    nationality: "Argentina",
    clubs: ["F.C. Barcelona", "Paris Saint German"],
    totalUEFACup: 5,
    totalBallonDor: 7,
    fifaWorldCup: 1,
  },
  {
    id: 2,
    firstName: "Cristiano",
    lastName: "Ronaldo",
    age: 38,
    nationality: "Portual",
    clubs: ["Manchester United", "Real Madrid", "joventus", "Al-Nassar"],
    totalUEFACup: 5,
    totalBallonDor: 5,
    fifaWorldCup: 0,
  },
  {
    id: 3,
    firstName: "Naymar",
    lastName: "da Silva Santos Júnior",
    age: 31,
    nationality: "Brazil",
    clubs: ["F.C. Barcelona", "Paris Saint German"],
    totalUEFACup: 1,
    totalBallonDor: 0,
    fifaWorldCup: 0,
  },
];
